### ISSUE TITLE
heredoc bug

### ISSUE THREAD

**Issue by Gamouche** [jjaniec/21sh#20]
lancer la commande 'cat <<' doit entrainer un parse error, mais le 21sh ne se comporte pas comme il devrait. carotte

**Comment by SebastienBruckert** [comment]
Making a new branch from develop.
First, because of the make, the prompt is not showing in the right place, it is in the beginning of the line when it makes
```
$ make && ./21sh
%> 	objs/main.o                   [=================================================================================>] -       81/      71
```

**Comment by SebastienBruckert** [comment]
Heredoc problem is now fix.
When there is a token like `<<` or `<<-`, next token need to be a `T_WORD`
