### ISSUE TITLE
Prompt + make

### ISSUE THREAD

**Issue by SebastienBruckert** [jjaniec/21sh#21]
When compiling with `make && ./21sh`, the prompt is not showing in the right place (AFTER the make output)
```
$ make && ./21sh
%> 	objs/main.o                   [=================================================================================>] -       81/      71
```

**Comment by Gamouche** [comment]
###### OBJ RULES ######
$(OBJ_DIR)%.o : $(SRC_DIR)%.c $(addprefix $(INCLUDES_DIR), $(INCLUDES_NAME))
	@mkdir -p $(OBJ_DIR) $(addprefix $(OBJ_DIR), $(OBJ_SUBDIRS))
	@$(CC) $(CFLAGS) -c $(IFLAGS) $< -o $@ && $(call ui_line, $@, $(NAME))
        @printf "\n"


ajoutez le printf "\n" et voilà
